<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxConverter" Version="0.22.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
    <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D2G.Iris.ML\D2G.Iris.ML.csproj" />
  </ItemGroup>

</Project>